billbuddy_test/billbuddy_test/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('shoestore/', include('shoestore.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

billbuddy_test/shoestore/urls.py
from django.urls import path

from . import views

app_name='shoestore'
urlpatterns = [
    path('', views.index, name='index'),
    path('basket/', views.basket, name='basket'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('brand/<int:brand_name>/', views.detail, name='brands'),
    path('<int:product_id>/buy/', views.buy, name='buy'),
]

billbuddy_test/shoestore/models.py
from django.db import models
from django.contrib.auth.models import User

class Brand(models.Model):
    brand_name = models.CharField(max_length=20)

    def __str__(self):
        return self.brand_name

class Product(models.Model):
  brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
  product_name = models.CharField(max_length=50)
  product_desc = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')
  price = models.DecimalField(max_digits=5, decimal_places=2)
  stock_no = models.IntegerField()

  def __str__(self):
        return self.product_name
        
class Order(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  pub_date = models.DateTimeField('date published')

  def __str__(self):
        return str(self.id)

class Orderitem(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  order = models.ForeignKey(Order, on_delete=models.CASCADE)

  def __str__(self):
        return str(self.id)

billbuddy_test/shoestore/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
import datetime
from django.conf import settings
from django.utils.timezone import make_aware

from .models import *

def index(request):
  newest_products_list = Product.objects.order_by('-pub_date')
  brand_list = Brand.objects.all()
  context = {'newest_products_list': newest_products_list, 'brand_list': brand_list}
  return render(request, 'shoestore/index.html', context)
  
def basket(request):
  order = Order.objects.filter(user = request.user)
  print(order)
  orderitem_list = Orderitem.objects.filter(order = order[0])
  context = {'orderitem_list': orderitem_list}
  return render(request, 'shoestore/basket.html', context)

def brands(request, brand):
  brand_products_list = Product.objects.filter(brand=brand).order_by('-pub_date')
  context = {'brand_products_list': brand_products_list}
  return render(request, 'shoestore/brands.html', context)

def detail(request, product_id):
  product = Product.objects.get(pk=product_id)
  context = {'product': product}
  return render(request, 'shoestore/detail.html', context)

def createorder(request):
  settings.TIME_ZONE
  try:
    ordercheck = Order.objects.get(user = request.user)
    return ordercheck
  except:
    order = Order(user = request.user, pub_date = make_aware(datetime.datetime.now()))
    order.save()
    return order

def buy(request, product_id):
  product = get_object_or_404(Product, pk=product_id)
  orderitem = Orderitem(product = product, order = createorder(request))
  orderitem.save()
  return HttpResponseRedirect(reverse('shoestore:index'))

# from https://wsvincent.com/django-user-authentication-tutorial-signup/
class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

billbuddy_test/shoestore/templates/shoestore/base.html
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css">
    <title>ShoeStore</title>
  </head>
  <body>
      <div class="pb-2 mt-4 mb-2 border-bottom">
        <div class="container">
          <div class="row">
            <div class="col text-left">
              <a href="/shoestore/">Online Shoe Store</a>
            </div>
            <div class="col text-right">
              {% if user.is_authenticated %}
                Hi {{ user.username }}!
                <p><a href="{% url 'logout' %}">logout</a></p>
              {% else %}
                <p>You are not logged in</p>
                <a href="{% url 'login' %}">login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </body>
  {% block content %}
    
  {% endblock %}
</html>

billbuddy_test/shoestore/templates/shoestore/basket.html
{% extends "base.html" %}

{% block content %}
<body>
  <div class="container fluid">
    <div class="row">
      <div class="col-md">
        <div class="row mb-5">
          <div class="text align-middle"><h2>View your order</h2></div>
        </div>
      </div>
    </div>
    <div class="row">
      {% if orderitem_list %}
        {% for product in orderitem_list %}
          <div class="card border" style="width: 18rem;">
              <img class="card-img-top" src="..." alt="Placeholder">
              <div class="card-body">
                <h5 class="card-title">{{product.product_name}}</h5>
                <p class="card-text">{{product.product_description}}</p>
                <div class="row">
                  <a href="{% url 'shoestore:detail' product.product.id %}" class="btn btn-primary">View product details</a>
                </div>
              </div>
            </div>
        {% endfor %}
      {% else %}
        <p>No items in order.</p>
      {% endif %}
    </div>
  </div>  
</body>
{% endblock %}

billbuddy_test/shoestore/templates/shoestore/brands.html
{% extends "base.html" %}

{% block content %}
<body>
  <div class="container fluid">
    <div class="col-9">
      <div class="row mb-5">
        <div class="text align-middle"><h2>Filter by brand</h2></div>
      </div>
    </div>
    <div class="col">
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown button
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" >Action</a>
        </div>
      </div>
    </div>
    <div class="row">
      {% if brand_products_list %}
        {% for product in newest_products_list %}
          <div class="card border" style="width: 18rem;">
              <img class="card-img-top" src="..." alt="Placeholder">
              <div class="card-body">
                <h5 class="card-title">{{product.product_name}}</h5>
                <p class="card-text">{{product.product_description}}</p>
                <a href="/shoestore/{{ product.id }}/" class="btn btn-primary">View product details</a>
              </div>
            </div>
        {% endfor %}
      {% else %}
        <p>No products are available.</p>
      {% endif %}
    </div>
  </div>  
</body>
{% endblock %}

billbuddy_test/shoestore/templates/shoestore/detail.html
{% extends "base.html" %}

{% block content %}
<body>
  <div class="container fluid">
    {% if product %}
    <div style="background:transparent !important" class="jumbotron">
      <h1 class="display-4">{{product.product_name}}</h1>
      <p class="lead">{{product.product_desc}}</p>
      <p class="lead">£{{product.price}}</p>
      <hr class="my-4">
      <form action="{% url 'shoestore:buy' product.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success" value="{{product.id}}">Add to basket</div>
      </form>
    </div>
    {% else %}
      <p>Something went wrong.</p>
    {% endif %}
  </div>  
</body>
{% endblock %}

billbuddy_test/shoestore/templates/shoestore/index.html
{% extends "base.html" %}

{% block content %}
<body>
  <div class="container fluid">
    <div class="row">
      <div class="col-md">
        <div class="row mb-5">
          <div class="text align-middle"><h2>Welcome to the online shoe store</h2></div>
        </div>
      </div>
      <div class="col-md">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filter by brand
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% if brand_list %}
                {% for brand in brand_list %}
                  <a class="dropdown-item" href="/shoestore/brands/{{brand.brand_name}}/">{{brand.brand_name}}</a>
                {% endfor %}
              {% endif %}
          </div>
        </div>
      </div>
      <div class="col-md">
        <a href="/shoestore/basket" class="btn btn-primary">View basket</a>
      </div>
    </div>
    <div class="row">
      {% if newest_products_list %}
        {% for product in newest_products_list %}
          <div class="card border" style="width: 18rem;">
              <img class="card-img-top" src="..." alt="Placeholder">
              <div class="card-body">
                <h5 class="card-title">{{product.product_name}}</h5>
                <p class="card-text">{{product.product_description}}</p>
                <div class="row">
                  <a href="{% url 'shoestore:detail' product.id %}" class="btn btn-primary">View product details</a>
                  <form action="{% url 'shoestore:buy' product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success" value="{{product.id}}">Add to basket</div>
                  </form>
                </div>
              </div>
            </div>
        {% endfor %}
      {% else %}
        <p>No products are available.</p>
      {% endif %}
    </div>
  </div>  
</body>
{% endblock %}

billbuddy_test/templates/signup.html
<!-- from tutorial https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/ -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}